name: Deploy Projeto Estatico Aluno

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # --- NOVO PASSO: Configurar Python ---
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # --- NOVO PASSO: Gerar o Index Dinâmico ---
      - name: Gerar Portal de Projetos
        run: |
          python3 generate_index.py

      - name: Enviar HTML/CSS para o Servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY}}
          # O source agora inclui o index.html gerado no passo anterior
          source: "./*" 
          target: "/var/inetpub/wwwroot/projetos/${{ vars.ALUNO_RA }}/${{ vars.ALUNO_PROJETO }}/"
          strip_components: 0

      - name: Ajustar Permissões (Opcional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R ubuntu:www-data /var/inetpub/wwwroot/projetos/${{ vars.ALUNO_RA }}
            chmod -R 755 /var/inetpub/wwwroot/projetos/${{ vars.ALUNO_RA }}