name: Deploy Projeto Estatico Aluno

on:
  push:
    branches: [ main, master ]

# Definimos as variáveis de ambiente para facilitar a manutenção

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Enviar HTML/CSS para o Servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.key_alunos }}
          # Envia tudo (*), mas você pode filtrar apenas arquivos específicos
          source: "./*" 
          # O caminho final será: /var/inetpub/wwwroot/projetos/202412345/site-turing/
          target: "${{ vars.REMOTE_TARGET }}/${{ vars.ALUNO_RA }}/${{ vars.PROJETO_ALUNO }}/"
          strip_components: 0 # Mantém a estrutura de pastas se houver subpastas (css, img)

      - name: Ajustar Permissões (Opcional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.key_alunos }}
          script: |
            sudo chown -R ubuntu:www-data ${{ vars.REMOTE_TARGET }}/${{ vars.ALUNO_RA }}
            chmod -R 755 ${{ vars.REMOTE_TARGET }}/${{ vars.ALUNO_RA }}